version: '2'

services:

#   consul cluster
  consul1:
    image: consul
    command: consul agent -server -client=0.0.0.0 -bootstrap-expect=3 -data-dir=/tmp/consul -ui
    hostname: consul1
    ports:
      - "8301:8300"
      - "8401:8400"
      - "8501:8500"
      - "8601:8600"
      - "9001:9001"

  consul2:
    image: consul
    command: consul agent -server -client=0.0.0.0 -bootstrap-expect=3 -rejoin -retry-join=consul1 -data-dir=/tmp/consul -ui
    hostname: consul2
    links:
      - consul1
    ports:
      - "8302:8300"
      - "8402:8400"
      - "8502:8500"
      - "8602:8600"
      - "9002:9001"
    depends_on:
      - consul1

  consul3:
    image: consul
    command: consul agent -server -client=0.0.0.0 -bootstrap-expect=3 -rejoin -retry-join=consul1 -data-dir=/tmp/consul -ui
    hostname: consul3
    links:
      - consul1
    ports:
      - "8303:8300"
      - "8403:8400"
      - "8503:8500"
      - "8603:8600"
      - "9003:9001"
    depends_on:
      - consul1

# replicas
  backend1:
    build: ../example
    image: zhenik/akka-http-example
    environment:
      - DISCOVERY_HOST=consul1
      - APPLICATION_HOST=backend1
#uncomment ports for debug
#    ports:
#    - "8881:3000"
    depends_on:
      - consul1

  backend2:
    build: ../example
    image: zhenik/akka-http-example
    environment:
      - DISCOVERY_HOST=consul2
      - APPLICATION_HOST=backend2
    depends_on:
      - consul2

  backend3:
    build: ../example
    image: zhenik/akka-http-example
    environment:
      - DISCOVERY_HOST=consul3
      - APPLICATION_HOST=backend3
    depends_on:
      - consul3

  nginx:
    build: ../
    image: seges/nginx-consul
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      #      templates
      - "./nginx-setup/templates/template.ctmpl:/etc/consul-template/templates/template.ctmpl"
      #      config
      - "./nginx-setup/conf:/etc/consul-template/conf"
    depends_on:
      - consul1